[package]
name = "firmware-updater"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
embedded-hal-async = "0.1.0-alpha.1"
drogue-ajour-protocol = "0.5.0"
heapless = "0.7"

serde_cbor = { version = "0.11", optional = true }
embedded-io = { version = "0.3.0", features = ["async"], optional = true }
embedded-nal-async = { git = "https://github.com/lulf/embedded-nal.git", branch = "shared-stack", optional = true }
embedded-tls = { git = "https://github.com/drogue-iot/embedded-tls", features = ["async"], branch = "main", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = ["drogue"]
drogue = ["embedded-io", "embedded-nal-async", "embedded-tls", "serde_cbor"]
