[package]
name = "embedded-dfu-ota"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drogue-ajour-protocol = { version = "0.2.0" }
serde_cbor = "0.11"
embedded-io = "0.3.0"
