[package]
name = "embedded-update"
version = "0.1.0"
edition = "2021"
resolver = "2"
description = "Firmware updates for embedded devices"
documentation = "https://docs.rs/embedded-update"
readme = "README.md"
homepage = "https://drogue.io"
repository = "https://github.com/drogue-iot/embedded-update"
authors = [
    "Ulf Lilleengen <lulf@redhat.com>"
]
license = "Apache-2.0"
keywords = ["embedded", "async", "dfu", "no_std", "ota"]
exclude = [".github"]

[dependencies]
defmt = { version = "0.3.0", optional = true }
embedded-hal-async = "0.1.0-alpha.1"
heapless = "0.7"
futures = { version =  "0.3", default-features = false }
serde = { version = "1", features = ["derive"], default-features = false }

#serde_cbor = { version = "0.11", optional = true, default-features = false }
#embedded-io = { version = "0.3.0", features = ["async"], optional = true }
#embedded-nal-async = { git = "https://github.com/lulf/embedded-nal.git", branch = "shared-stack", optional = true }
#embedded-tls = { git = "https://github.com/drogue-iot/embedded-tls", features = ["async"], branch = "main", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde_cbor = { version = "0.11", features = ["std"] }

[features]
defmt = ["dep:defmt"]
#default = ["drogue"]
#drogue = ["embedded-io", "embedded-nal-async", "embedded-tls", "serde_cbor"]
